<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  // 'APP_SECRET' => 'a8255cedf849cb84aca9642131f20a68',
  'APP_SECRET' => '1b6cba845c9a73e9babb3804d0dc31a6',
  'DATABASE_URL' => 'mysql://root:lionPass@db:3306/PlantDB?serverVersion=5.7'
);
